services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.prod.Dockerfile
    working_dir: /home/frontend
    volumes:
      - ./frontend:/home/frontend
    ports:
      - 127.0.0.1:3000:3000
    command: ["./run.sh"]
    depends_on:
      - backend
    tty: true
    networks:
      - storage
    
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.prod.Dockerfile
    volumes:
      - ./backend:/go/src/github.com/YahiroRyo/yappi_storage/backend
      - ./storage:/~/storage
    tty: true
    command: ["./run.sh"]
    depends_on:
      - postgres
      - redis
    networks:
      - storage

  redis:
    build:
      context: .
      dockerfile: ./docker/redis.prod.Dockerfile
    volumes:
    - ./redis/data:/data
    command: ["redis-server"]
    networks:
      - storage

  postgres:
    build: 
      context: .
      dockerfile: ./docker/postgres.prod.Dockerfile
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
      - ./database/logs:/var/log
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: 'main'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Asia/Tokyo"
      LC_ALL: "C.UTF-8"
    networks:
      - storage

networks:
  storage:
    driver: bridge